services:
  - type: web
    name: ai-chat-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_WS_URL
        value: https://chat-bot-4oy4.onrender.com
